# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from odoo import api, fields, models, tools, _
from odoo.exceptions import UserError, ValidationError
from odoo.osv import expression


class ProductAttributeValue(models.Model):
    _inherit = "product.attribute.value"

    code = fields.Char('缩写码', required=False)


class ProductTemplateAttributeValue(models.Model):
    """Materialized relationship between attribute values
    and product template generated by the product.template.attribute.line"""

    _inherit = "product.template.attribute.value"

    @api.model
    def _name_search(self, name, args=None, operator='ilike', limit=100, name_get_uid=None):
        # Timwang modified at 2021/9/17
        # 导入变体数据是，可以根据"父物料编码: 属性名称: 属性值"的格式找到相应的属性值行
        args = args or []
        if operator == 'ilike' and not (name or '').strip():
            domain = []
        else:
            strlist = str.split(name, ": ")
            if len(strlist) == 3:
                domain = [("product_tmpl_id.default_code", "=", strlist[0]),
                          ("attribute_id.name", "=", strlist[1]),
                          ("product_attribute_value_id.name", "=", strlist[2])]
            else:
                domain = []
        return self._search(expression.AND([domain, args]), limit=limit, access_rights_uid=name_get_uid)
